/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoId = IDL.Text;
export const UserId = IDL.Principal;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const VideoResponse = IDL.Record({
  'id' : VideoId,
  'title' : IDL.Text,
  'creator' : UserId,
  'description' : IDL.Text,
  'videoFile' : ExternalBlob,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'points' : IDL.Nat,
});
export const ProfileResponse = IDL.Record({
  'name' : IDL.Text,
  'points' : IDL.Nat,
});
export const Time = IDL.Int;
export const WatchRecordResponse = IDL.Record({
  'timestamp' : Time,
  'videoId' : VideoId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Text], [], []),
  'getAllVideos' : IDL.Func([], [IDL.Vec(VideoResponse)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPointsBalance' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getProfile' : IDL.Func([], [ProfileResponse], ['query']),
  'getProfileVideos' : IDL.Func([UserId], [IDL.Vec(VideoResponse)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([VideoId], [VideoResponse], ['query']),
  'getWatchHistory' : IDL.Func(
      [UserId],
      [IDL.Vec(WatchRecordResponse)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadVideo' : IDL.Func(
      [VideoId, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'watchVideo' : IDL.Func([VideoId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoId = IDL.Text;
  const UserId = IDL.Principal;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const VideoResponse = IDL.Record({
    'id' : VideoId,
    'title' : IDL.Text,
    'creator' : UserId,
    'description' : IDL.Text,
    'videoFile' : ExternalBlob,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'points' : IDL.Nat,
  });
  const ProfileResponse = IDL.Record({ 'name' : IDL.Text, 'points' : IDL.Nat });
  const Time = IDL.Int;
  const WatchRecordResponse = IDL.Record({
    'timestamp' : Time,
    'videoId' : VideoId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Text], [], []),
    'getAllVideos' : IDL.Func([], [IDL.Vec(VideoResponse)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPointsBalance' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getProfile' : IDL.Func([], [ProfileResponse], ['query']),
    'getProfileVideos' : IDL.Func(
        [UserId],
        [IDL.Vec(VideoResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([VideoId], [VideoResponse], ['query']),
    'getWatchHistory' : IDL.Func(
        [UserId],
        [IDL.Vec(WatchRecordResponse)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadVideo' : IDL.Func(
        [VideoId, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'watchVideo' : IDL.Func([VideoId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };